name: CI

on:
    - pull_request

jobs:
    typecheck:
        name: Typecheck
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v3

            - name: Set up Node 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'pnpm'

            - name: Install dependencies
              run: pnpm install

            - name: Typecheck
              run: |
                  pnpm typecheck

    test-build:
        name: Test production build
        runs-on: ubuntu-20.04
        steps:
            - uses: actions/checkout@v2

            - name: Set up Node 18
              uses: actions/setup-node@v3
              with:
                  node-version: 18
                  cache: 'pnpm'

            - name: Install dependencies
              if: steps.node-modules-cache.outputs.cache-hit != 'true'
              run: pnpm install --frozen-lockfile

            - name: Build
              run: |
                  pnpm build
