name: Readme sync

on:
  - pull_request

jobs:

  sync-readmes:
    name: Sync World ID READMEs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules
      
      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Compile script to JS
        run: ./node_modules/typescript/bin/tsc readme-sync.ts
      
      - name: Sync local README
        run: node readme-sync.js

      - name: Commit changes to repository
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: sync shared README content
          commit_options: '--no-verify --signoff'
          file_pattern: README.md
          commit_author: GitHub Actions <actions@github.com>
      
      - name: Sync remote READMEs
        run: node readme-sync.js remote