name: Readme sync

on:
  pull_request:
    types: [closed]
    paths:
      - 'SHARED-README.md'
      - 'repositories.json'

jobs:

  sync-remote-readme:
    name: Sync all World ID READMEs
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Node 16
        uses: actions/setup-node@v1
        with:
          node-version: 16

      - uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: |
            node_modules
          key: ${{ runner.os }}-node-modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-modules
      
      - name: Install dependencies
        if: steps.node-modules-cache.outputs.cache-hit != 'true'
        run: yarn install --frozen-lockfile

      - name: Compile script to JS
        run: ./node_modules/typescript/bin/tsc readme-sync.ts
      
      - name: Sync remote READMEs
        env:
          GITHUB_TOKEN: ${{ secrets.WLD_ID_SYNC }}
        run: node readme-sync.js remote